//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public long cartID { get; set; }
        public Nullable<long> customerID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
