//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.ActionLogs = new HashSet<ActionLog>();
            this.Discounts = new HashSet<Discount>();
            this.Orders = new HashSet<Order>();
        }
    
        public long customerID { get; set; }
        public string customerName { get; set; }
        public string customerMail { get; set; }
        public Nullable<int> customerSex { get; set; }
        public string customerUserName { get; set; }
        public string customerPassword { get; set; }
        public string customerPhoto { get; set; }
        public Nullable<long> idAddress { get; set; }
        public Nullable<long> cartID { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public Nullable<int> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionLog> ActionLogs { get; set; }
        public virtual Cart Cart { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discount> Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
