//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long customerID { get; set; }
        public string customerName { get; set; }
        public string customerSex { get; set; }
        public string customerUserName { get; set; }
        public string customerPassword { get; set; }
        public string customerPhoto { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
    }
}
