//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public long ID { get; set; }
        public Nullable<long> customerID { get; set; }
        public string customerAdd { get; set; }
        public string customerPhone { get; set; }
        public Nullable<int> isMain { get; set; }
        public string customerMail { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
