//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int ID { get; set; }
        public Nullable<long> emID { get; set; }
        public string fullName { get; set; }
        public string sex { get; set; }
        public string photo { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string posID { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> addressID { get; set; }
        public Nullable<int> isActive { get; set; }
    }
}
