//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDetail()
        {
            this.Salaries = new HashSet<Salary>();
        }
    
        public long emID { get; set; }
        public string fullName { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string sex { get; set; }
        public string photo { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public Nullable<int> posID { get; set; }
        public Nullable<int> roleID { get; set; }
        public string address { get; set; }
        public Nullable<int> isActive { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Position Position { get; set; }
        public virtual Position Position1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
    }
}
