//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long notiID { get; set; }
        public Nullable<long> sendUserID { get; set; }
        public string sendUserFullName { get; set; }
        public Nullable<long> receiveUserID { get; set; }
        public string receiveUserFullName { get; set; }
        public Nullable<long> objectID { get; set; }
        public Nullable<long> objectTypeID { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public string image { get; set; }
        public Nullable<long> menutype { get; set; }
    }
}
