//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderDetailID { get; set; }
        public Nullable<long> orderID { get; set; }
        public Nullable<long> productID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<long> Money { get; set; }
        public string idAdd { get; set; }
        public Nullable<int> statusID { get; set; }
        public Nullable<long> price { get; set; }
    }
}
