//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int posID { get; set; }
        public string posName { get; set; }
    }
}
