//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessOrder()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public long processID { get; set; }
        public Nullable<long> objectID { get; set; }
        public string shippingName { get; set; }
        public Nullable<long> sendUserID { get; set; }
        public string sendUserFullName { get; set; }
        public Nullable<System.DateTime> sendDate { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
        public Nullable<long> receiveUserID { get; set; }
        public string receiveUserFullName { get; set; }
        public Nullable<int> processType { get; set; }
        public Nullable<int> status { get; set; }
        public string description { get; set; }
        public Nullable<int> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
