//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long productID { get; set; }
        public string productName { get; set; }
        public Nullable<long> productQuantity { get; set; }
        public Nullable<long> productPrice { get; set; }
        public string productDescribe { get; set; }
        public string productImage { get; set; }
        public Nullable<int> productTypeID { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
