//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_Web_MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public long ID { get; set; }
        public Nullable<long> emID { get; set; }
        public Nullable<long> salary1 { get; set; }
        public Nullable<long> bonus { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
    }
}
