//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoonShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customerID { get; set; }
        public Nullable<System.Guid> customerCode { get; set; }
        public string customerName { get; set; }
        public string customerSex { get; set; }
        public string customerAddress { get; set; }
        public string customerUserName { get; set; }
        public string customerPassword { get; set; }
        public string customerPhoto { get; set; }
    }
}
